//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEmpleados", ReplyAction="http://tempuri.org/IService1/ObtenerEmpleadosResponse")]
        System.Data.DataSet ObtenerEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEmpleados", ReplyAction="http://tempuri.org/IService1/ObtenerEmpleadosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerCobrador", ReplyAction="http://tempuri.org/IService1/ObtenerCobradorResponse")]
        System.Data.DataSet ObtenerCobrador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerCobrador", ReplyAction="http://tempuri.org/IService1/ObtenerCobradorResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCobradorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : crm.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<crm.ServiceReference1.IService1>, crm.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerEmpleados() {
            return base.Channel.ObtenerEmpleados();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerEmpleadosAsync() {
            return base.Channel.ObtenerEmpleadosAsync();
        }
        
        public System.Data.DataSet ObtenerCobrador() {
            return base.Channel.ObtenerCobrador();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCobradorAsync() {
            return base.Channel.ObtenerCobradorAsync();
        }
    }
}
